#!/bin/env bash
clear
source `dirname $0`/portablehexo-welcome
echo ""
echo "                 欢迎使用比特萌 HEXO 便携版部署配置程序"
echo ""
#echo "    请根据提示输入您 Github 或 Coding.net 相关信息："
echo "        预期您需要提供的信息有：昵称、邮箱、Git 托管站用户名及分支名；"
echo ""
echo "     进行本步骤之前，您应当已注册并激活了您的 Github 或 Coding.net 账户，"
echo "        并已新建了对应的代码仓库：（相对应的以上两种托管站对应的格式分别如下）"
echo "                                 Github Pages    ： `echo -e "\033[32;49;1musername\033[39;49;0m"`.github.io"
echo "                                 Coding.net Pages： `echo -e "\033[32;49;1musername\033[39;49;0m"`.coding.me"
echo "                   这里的 `echo -e "\033[32;49;1musername\033[39;49;0m"` 为您的对应托管站用户名。"
echo ""
echo  "                准备好了？ 按下 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 键开始配置"
read
echo "     请您根据提示依次输入相关信息："
echo ""
echo "[1/3]、请输入您的 Github 或 Coding.net 的用户名，输入完毕 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 确认！"
read GITID
echo "[2/3]、请输入您的 Github 或 Coding.net 注册邮箱，输入完毕 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 确认！"
read GITEMAIL
echo "[3/3]、您使用的是 Github Pages 托管服务？（如是请输`echo -e "\033[32;49;1m YES \033[39;49;0m"`，否则直接回车下一步）"
read GITHUBHOSTING
echo "    感谢您的应答，您输入的信息为："
echo ""
echo "    用户名： `echo $GITID` | 电子邮箱：`echo $GITEMAIL` | Github Pages 托管：`echo $GITHUBHOSTING`"
echo ""
echo  "         以上输入的信息没有问题？ 按下 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 继续执行配置任务！"
read TEMPINPUT

#git config --global credential.helper store
git config --global push.default simple
git config --global user.name $GITID
git config --global user.email $GITEMAIL

if [[ $GITHUBHOSTING = [Yy][Ee][Ss] ]];then
    export HOSTING="git@github.com:$GITID/$GITID.github.io.git"
else
    export HOSTING="git@git.coding.net:$GITID/$GITID.coding.me.git"
fi

export HEXOCONFIG=/home/`whoami`/hexo/_config.yml

sed -i '/^  type:/d' $HEXOCONFIG
sed -i '/^  repo:/d' $HEXOCONFIG
sed -i '/^  branch:/d' $HEXOCONFIG
#sed -i '/^  message:/d' $HEXOCONFIG

sed -i '$a\  type: git' $HEXOCONFIG
sed -i '$a\  repo: '$HOSTING'' $HEXOCONFIG
sed -i '$a\  branch: master' $HEXOCONFIG
#sed -i '$a\  message: 更新博客。' $HEXOCONFIG

if [ $? -eq 0 ];then
    echo "                      您成功完成了对 HEXO 部署配置，"
    echo ""
    echo "                 更多的配置请参照 HEXO 官方简体中文文档，"
    echo "             自行调整博客站点主目录下的 `echo -e "\033[32;49;1m_config.yml\033[39;49;0m"` 主配置文件。 "
    echo "                     https://hexo.io/zh-cn/docs/"
    echo ""
else
    echo ""
    echo "                     很遗憾，您未能完成了对 HEXO 部署配置，"
    echo "             您可以选择："
    echo ""
    echo "         1、向我们 Github 项目地址发送问题报告或者提交修复方案："
    echo "             https://github.com/Bitmoe/PortableHexo/issues"
    echo ""
    echo "         2、向我们官方产品论坛发送问题报告或者提交修复方案："
    echo "                https://bbs.bitmoe.cn/PortableHexo/"
    echo ""
    echo "         3、向非官方的 HEXO 讨论 QQ 群 ：287306637 报告问题。"
    echo ""
    echo "               感谢您对 `echo -e "\033[32;49;1m比特萌 HEXO 便携版\033[39;49;0m"` 项目的支持！ "
fi

#echo "`tail -n 4 $HEXOCONFIG`"
#echo ""
#echo "推送部署信息配置成功，相关信息如上；按下 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 键退出本配置程序。"
#read TEMPINPUT