#!/bin/env bash
clear
source `dirname $0`/portablehexo-welcome
echo ""
echo "                 欢迎使用比特萌 HEXO 便携版辅助配置程序"
echo ""
echo "    请根据提示输入您博客站点相关信息："
echo "        预期您需要提供的信息有：主标题、副标题、描述、作者、网站地址；"
echo ""
echo  "              准备好了？ 按下 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 键开始配置"
read

echo "1、请输入您博客站点的主标题："
read blogTitle
echo "2、请输入您博客站点的副标题："
read blogSubTitle
echo "3、请输入您博客站点的描述："
echo "   - 主要用于搜索引擎索引之用；"
read blogDescription
echo "4、请输入您博客站点的作者或者您的昵称："
read blogAuthor
echo "5、请输入您博客站点的网站地址："
echo ""
echo "   - 如果托管在 Github Pages 之上请输入 `echo -e "\033[32;49;1m用户名.github.io\033[39;49;0m"` 的格式"
echo "       - 例如： `echo -e "\033[32;49;1mbitmoe\033[39;49;0m"`.github.io ，`echo -e "\033[32;49;1mbitmoe\033[39;49;0m"` 是我们的 Github 用户名；"
echo ""
echo "   - 如果托管在 Coding.net Pages 请输入 `echo -e "\033[32;49;1m用户名.coding.me\033[39;49;0m"` 的格式"
echo "       - 例如： `echo -e "\033[32;49;1mbitmoe\033[39;49;0m"`.coding.me ，`echo -e "\033[32;49;1mbitmoe\033[39;49;0m"` 是我们的 Coding.net 用户名；"
echo ""
echo "   - 如果您拥有自己的域名请输入 `echo -e "\033[32;49;1mxxxxxxxx.xxx\033[39;49;0m"` 的格式"
echo "       - 例如： `echo -e "\033[32;49;1mbitmoe.com\033[39;49;0m"` ，"
echo "       - 当然，是否使用三级域名是 `echo -e "\033[32;49;1mwww\033[39;49;0m"`.bitmoe.cn 或者 `echo -e "\033[32;49;1mportablehexo\033[39;49;0m"`.bitmoe.cn；"
echo "       - 只要您愿意，随您高兴 XD 。"
echo ""
read blogUrl

export HEXOCONFIG=/home/`whoami`/hexo/_config.yml
export HEXOCNAME=/home/`whoami`/hexo/source/CNAME

sed -i '/^title: /c\title: '$blogTitle'' $HEXOCONFIG
sed -i '/^subtitle:/c\subtitle: '$blogSubTitle'' $HEXOCONFIG
sed -i '/^description:/c\description: '$blogDescription'' $HEXOCONFIG
sed -i '/^author:/c\author: '$blogAuthor'' $HEXOCONFIG
echo $blogUrl > $HEXOCNAME
sed -i '/^url: /c\url: '$blogUrl'' $HEXOCONFIG

if [ $? -eq 0 ];then
    echo "                     您成功完成了对 HEXO 初始化配置，"
    echo "                 更多的配置请参照 HEXO 官方简体中文文档，"
    echo "             自行调整博客站点主目录下的 `echo -e "\033[32;49;1m_config.yml\033[39;49;0m"` 主配置文件。 "
    echo "                     https://hexo.io/zh-cn/docs/"
    echo ""
else
    echo ""
    echo "                    很遗憾，您未能完成了对 HEXO 初始化配置，"
    echo "             您可以选择："
    echo ""
    echo "         1、向我们 Github 项目地址发送问题报告或者提交修复方案："
    echo "             https://github.com/Bitmoe/PortableHexo/issues"
    echo ""
    echo "         2、向我们官方产品论坛发送问题报告或者提交修复方案："
    echo "                https://bbs.bitmoe.cn/PortableHexo/"
    echo ""
    echo "         3、向非官方的 HEXO 讨论 QQ 群 ：287306637 报告问题。"
    echo ""
    echo "               感谢您对 `echo -e "\033[32;49;1m比特萌 HEXO 便携版\033[39;49;0m"` 项目的支持！ "
fi

#if [[ $? -eq 0 ]];then A else b;fi
#echo "HEXO 的初步配置完毕，更多的配置请参考官方文档~自带中文哦！"
#echo "本脚本由 比特萌公司（Bitmoe Inc.） 编写并提供技术支持！"
#read TEMPINPUT
