#!/bin/env bash
clear
source `dirname $0`/portablehexo-welcome
echo ""
echo "                 欢迎使用比特萌 HEXO 便携版本地调试程序"
echo ""
echo ""
echo ""
echo "          若显示 Hexo is running ，浏览器却打不开链接，请更换端口；"
echo "             您可以在指令模式下输入 cd hexo && hexo s `echo -e "\033[32;49;1m-p6666\033[39;49;0m"` 。"
echo "                       `echo -e "\033[32;49;1m-p6666\033[39;49;0m"` 表示使用 `echo -e "\033[32;49;1m6666\033[39;49;0m"` 号端口"
echo ""
echo ""
echo "        如需 `echo -e "\033[32;49;1m 取消 \033[39;49;0m"` 本地调试按 `echo -e "\033[32;49;1m [ Crtl ] \033[39;49;0m"` + `echo -e "\033[32;49;1m [ C ] \033[39;49;0m"` 键"
echo ""
echo "    按下 `echo -e "\033[32;49;1m [ Enter ] \033[39;49;0m"` 键启动调试指令"
read TEMPINPUT
cd /home/`whoami`/hexo
hexo s --debug
echo ""
echo "回车退出"
read TEMPINPUT